import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  useEffect(() => {
    const text = "Welcome to Clipboard Fun"
    navigator.clipboard.writeText(text)
      .then(() => {
        console.log('Async: Copying to clipboard was successful!');
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Clipboard Fun
        </h1>
        <p className={styles.description}>
          This is a simple app that will copy the text "Welcome to Clipboard Fun" to the clipboard. Without asking you for permission.
        </p>
      </main>
    </div>
  )
}
