import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  useEffect(() => {
    const text = "Welcome to Clipboard Fun"
    navigator.clipboard.writeText(text)
      .then(() => {
        window.alert("check your clipboard, I copied this text: " + text);
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Clipboard Fun
        </h1>


      </main>
    </div>
  )
}
